/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/[...path]': RouteRecordInfo<'/[...path]', '/:path(.*)', { path: ParamValue<true> }, { path: ParamValue<false> }>,
    '/about': RouteRecordInfo<'/about', '/about', Record<never, never>, Record<never, never>>,
    '/components/': RouteRecordInfo<'/components/', '/components', Record<never, never>, Record<never, never>>,
    '/components/SakuraArticle': RouteRecordInfo<'/components/SakuraArticle', '/components/SakuraArticle', Record<never, never>, Record<never, never>>,
    '/components/SakuraArticleCategories': RouteRecordInfo<'/components/SakuraArticleCategories', '/components/SakuraArticleCategories', Record<never, never>, Record<never, never>>,
    '/components/SakuraArticleCollapse': RouteRecordInfo<'/components/SakuraArticleCollapse', '/components/SakuraArticleCollapse', Record<never, never>, Record<never, never>>,
    '/components/SakuraArticleFooter': RouteRecordInfo<'/components/SakuraArticleFooter', '/components/SakuraArticleFooter', Record<never, never>, Record<never, never>>,
    '/components/SakuraArticleTags': RouteRecordInfo<'/components/SakuraArticleTags', '/components/SakuraArticleTags', Record<never, never>, Record<never, never>>,
    '/components/SakuraBackgroundDisplay': RouteRecordInfo<'/components/SakuraBackgroundDisplay', '/components/SakuraBackgroundDisplay', Record<never, never>, Record<never, never>>,
    '/components/SakuraBanner': RouteRecordInfo<'/components/SakuraBanner', '/components/SakuraBanner', Record<never, never>, Record<never, never>>,
    '/components/SakuraCard': RouteRecordInfo<'/components/SakuraCard', '/components/SakuraCard', Record<never, never>, Record<never, never>>,
    '/components/SakuraCategories': RouteRecordInfo<'/components/SakuraCategories', '/components/SakuraCategories', Record<never, never>, Record<never, never>>,
    '/components/SakuraCategory': RouteRecordInfo<'/components/SakuraCategory', '/components/SakuraCategory', Record<never, never>, Record<never, never>>,
    '/components/SakuraFooter': RouteRecordInfo<'/components/SakuraFooter', '/components/SakuraFooter', Record<never, never>, Record<never, never>>,
    '/components/SakuraFooterNavigation': RouteRecordInfo<'/components/SakuraFooterNavigation', '/components/SakuraFooterNavigation', Record<never, never>, Record<never, never>>,
    '/components/SakuraGlitchText': RouteRecordInfo<'/components/SakuraGlitchText', '/components/SakuraGlitchText', Record<never, never>, Record<never, never>>,
    '/components/SakuraHamburger': RouteRecordInfo<'/components/SakuraHamburger', '/components/SakuraHamburger', Record<never, never>, Record<never, never>>,
    '/components/SakuraLinks': RouteRecordInfo<'/components/SakuraLinks', '/components/SakuraLinks', Record<never, never>, Record<never, never>>,
    '/components/SakuraNavbar': RouteRecordInfo<'/components/SakuraNavbar', '/components/SakuraNavbar', Record<never, never>, Record<never, never>>,
    '/components/SakuraNavbarBrand': RouteRecordInfo<'/components/SakuraNavbarBrand', '/components/SakuraNavbarBrand', Record<never, never>, Record<never, never>>,
    '/components/SakuraNavLink': RouteRecordInfo<'/components/SakuraNavLink', '/components/SakuraNavLink', Record<never, never>, Record<never, never>>,
    '/components/SakuraNetworkGraph': RouteRecordInfo<'/components/SakuraNetworkGraph', '/components/SakuraNetworkGraph', Record<never, never>, Record<never, never>>,
    '/components/SakuraNoticeBoard': RouteRecordInfo<'/components/SakuraNoticeBoard', '/components/SakuraNoticeBoard', Record<never, never>, Record<never, never>>,
    '/components/SakuraPageHeader': RouteRecordInfo<'/components/SakuraPageHeader', '/components/SakuraPageHeader', Record<never, never>, Record<never, never>>,
    '/components/SakuraSidebar': RouteRecordInfo<'/components/SakuraSidebar', '/components/SakuraSidebar', Record<never, never>, Record<never, never>>,
    '/components/SakuraSidebarCategory': RouteRecordInfo<'/components/SakuraSidebarCategory', '/components/SakuraSidebarCategory', Record<never, never>, Record<never, never>>,
    '/components/SakuraSidebarCategoryByName': RouteRecordInfo<'/components/SakuraSidebarCategoryByName', '/components/SakuraSidebarCategoryByName', Record<never, never>, Record<never, never>>,
    '/components/SakuraSideBarToggleButton': RouteRecordInfo<'/components/SakuraSideBarToggleButton', '/components/SakuraSideBarToggleButton', Record<never, never>, Record<never, never>>,
    '/components/SakuraSiteInfoCard': RouteRecordInfo<'/components/SakuraSiteInfoCard', '/components/SakuraSiteInfoCard', Record<never, never>, Record<never, never>>,
    '/components/SakuraSocialLinks': RouteRecordInfo<'/components/SakuraSocialLinks', '/components/SakuraSocialLinks', Record<never, never>, Record<never, never>>,
    '/components/SakuraTimeLine': RouteRecordInfo<'/components/SakuraTimeLine', '/components/SakuraTimeLine', Record<never, never>, Record<never, never>>,
    '/components/SakuraToc': RouteRecordInfo<'/components/SakuraToc', '/components/SakuraToc', Record<never, never>, Record<never, never>>,
    '/components/SakuraToTop': RouteRecordInfo<'/components/SakuraToTop', '/components/SakuraToTop', Record<never, never>, Record<never, never>>,
    '/components/SakuraTypewriter': RouteRecordInfo<'/components/SakuraTypewriter', '/components/SakuraTypewriter', Record<never, never>, Record<never, never>>,
    '/components/StarterAuthor': RouteRecordInfo<'/components/StarterAuthor', '/components/StarterAuthor', Record<never, never>, Record<never, never>>,
    '/components/StarterToggleLocale': RouteRecordInfo<'/components/StarterToggleLocale', '/components/StarterToggleLocale', Record<never, never>, Record<never, never>>,
    '/components/ValaxyCopyright': RouteRecordInfo<'/components/ValaxyCopyright', '/components/ValaxyCopyright', Record<never, never>, Record<never, never>>,
    '/docs/': RouteRecordInfo<'/docs/', '/docs', Record<never, never>, Record<never, never>>,
    '/docs/hello-valaxy': RouteRecordInfo<'/docs/hello-valaxy', '/docs/hello-valaxy', Record<never, never>, Record<never, never>>,
    '/docs/ocean': RouteRecordInfo<'/docs/ocean', '/docs/ocean', Record<never, never>, Record<never, never>>,
    '/hello-valaxy': RouteRecordInfo<'/hello-valaxy', '/hello-valaxy', Record<never, never>, Record<never, never>>,
    '/notes/': RouteRecordInfo<'/notes/', '/notes', Record<never, never>, Record<never, never>>,
    '/posts/iBook 1999/': RouteRecordInfo<'/posts/iBook 1999/', '/posts/iBook 1999', Record<never, never>, Record<never, never>>,
    '/posts/iMac 1998/': RouteRecordInfo<'/posts/iMac 1998/', '/posts/iMac 1998', Record<never, never>, Record<never, never>>,
    '/posts/iMac 1999/': RouteRecordInfo<'/posts/iMac 1999/', '/posts/iMac 1999', Record<never, never>, Record<never, never>>,
    '/posts/iMac 2003/': RouteRecordInfo<'/posts/iMac 2003/', '/posts/iMac 2003', Record<never, never>, Record<never, never>>,
    '/posts/iMac 2004/': RouteRecordInfo<'/posts/iMac 2004/', '/posts/iMac 2004', Record<never, never>, Record<never, never>>,
    '/posts/iMac 2005/': RouteRecordInfo<'/posts/iMac 2005/', '/posts/iMac 2005', Record<never, never>, Record<never, never>>,
    '/posts/iMac 2007/': RouteRecordInfo<'/posts/iMac 2007/', '/posts/iMac 2007', Record<never, never>, Record<never, never>>,
    '/posts/iPad 2010/': RouteRecordInfo<'/posts/iPad 2010/', '/posts/iPad 2010', Record<never, never>, Record<never, never>>,
    '/posts/iPhone 2007/': RouteRecordInfo<'/posts/iPhone 2007/', '/posts/iPhone 2007', Record<never, never>, Record<never, never>>,
    '/posts/iPhone4 2010/': RouteRecordInfo<'/posts/iPhone4 2010/', '/posts/iPhone4 2010', Record<never, never>, Record<never, never>>,
    '/posts/iPhone5C 2013/': RouteRecordInfo<'/posts/iPhone5C 2013/', '/posts/iPhone5C 2013', Record<never, never>, Record<never, never>>,
    '/posts/iPhoneX 2017/': RouteRecordInfo<'/posts/iPhoneX 2017/', '/posts/iPhoneX 2017', Record<never, never>, Record<never, never>>,
    '/posts/MacBookAir 2008/': RouteRecordInfo<'/posts/MacBookAir 2008/', '/posts/MacBookAir 2008', Record<never, never>, Record<never, never>>,
    '/posts/MacBookPro 2008/': RouteRecordInfo<'/posts/MacBookPro 2008/', '/posts/MacBookPro 2008', Record<never, never>, Record<never, never>>,
    '/posts/MacOSX 1999/': RouteRecordInfo<'/posts/MacOSX 1999/', '/posts/MacOSX 1999', Record<never, never>, Record<never, never>>,
    '/posts/PowerMacG3 1999/': RouteRecordInfo<'/posts/PowerMacG3 1999/', '/posts/PowerMacG3 1999', Record<never, never>, Record<never, never>>,
    '/posts/PowerMacG4 1999/': RouteRecordInfo<'/posts/PowerMacG4 1999/', '/posts/PowerMacG4 1999', Record<never, never>, Record<never, never>>,
    '/posts/PowerMacG4Cube 1999/': RouteRecordInfo<'/posts/PowerMacG4Cube 1999/', '/posts/PowerMacG4Cube 1999', Record<never, never>, Record<never, never>>,
    '/tags/': RouteRecordInfo<'/tags/', '/tags', Record<never, never>, Record<never, never>>,
  }
}
